name: managerapp
description: A new Flutter Manager App project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  get: ^4.6.5
  get_storage: ^2.1.1
  dio: ^5.1.1
  intl: ^0.18.0
  flutter_svg: ^2.0.5
  cached_network_image: ^3.2.3
  permission_handler: ^10.2.0
  device_info_plus: ^8.2.0
  package_info_plus: ^3.1.0
  percent_indicator: ^4.2.3
  store_redirect: ^2.0.1
  flutter_staggered_grid_view: ^0.4.0
  shimmer: ^2.0.0
  flutter_speed_dial: ^6.2.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  flutter_swipe_action_cell: ^3.1.0
  url_launcher: ^6.1.10
  image_picker: ^0.8.7+4
  flutter_image_compress: ^1.1.3






dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1


flutter:
  assets:
    - assets/images/


  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/comfortaa-regular.ttf
        - asset: assets/fonts/comfortaa-bold.ttf
          weight: 700

        - asset: assets/fonts/comfortaa-light.ttf

        - asset: assets/fonts/comfortaa-medium.ttf

        - asset: assets/fonts/comfortaa-thin.ttf

        - asset: assets/fonts/comfortaa-italic.ttf
         

  uses-material-design: true
